// Generated by CoffeeScript 1.7.1
var components, loadedComponents;

loadedComponents = ["todolist"];

components = loadedComponents.map(function(component) {
  return "forum/components/" + component + "/index";
});

define('forum/components/components_loader', components, function() {
  var c, i, _i, _len;
  components = Array.prototype.slice.call(arguments, 0);
  for (i = _i = 0, _len = components.length; _i < _len; i = ++_i) {
    c = components[i];
    c['name'] = loadedComponents[i];
  }
  return {
    components: components,
    config: {}
  };
});
